version: '3'

services:
  blog-api:
    build:
      context: .
      dockerfile: deploy/Dockerfile.api
    environment:
      - HOST=0.0.0.0
      - PORT=3030
      - NODE_ENV=production
      - BLOG_DATA_DIR=/srv/blog-data/seed
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - blog-data:/srv/blog-data
    ports:
      - "3030:3030"
    restart: always

volumes:
  blog-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
