#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const dataDir = path.resolve(process.cwd(), process.env.BLOG_DATA_DIR || 'data/seed');
const files = ['posts', 'categories', 'tags', 'nav', 'settings', 'issues', 'tools', 'sections', 'graphics'];

const sampleData = {
  posts: [
    {
      id: '1',
      title: 'Welcome to my blog',
      slug: 'welcome-to-my-blog',
      summary: 'A sample article generated by init-data.',
      content: '# Welcome to my blog\n\nThis is the first sample post.',
      categories: ['1'],
      categoryIds: ['1'],
      categoryId: '1',
      tags: ['1', '2'],
      tagIds: ['1', '2'],
      status: 'published',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      created_at: new Date().toISOString().slice(0, 10),
      updated_at: new Date().toISOString().slice(0, 10),
    },
  ],
  categories: [
    {
      id: '1',
      name: 'Tech Notes',
      slug: 'tech-notes',
      color: '#3498db',
      icon: 'code',
      order: 1,
      sectionId: '1',
    },
    {
      id: '2',
      name: 'Life',
      slug: 'life',
      color: '#e74c3c',
      icon: 'book',
      order: 2,
      sectionId: '2',
    },
  ],
  tags: [
    {
      id: '1',
      name: 'Vue',
      slug: 'vue',
    },
    {
      id: '2',
      name: 'JavaScript',
      slug: 'javascript',
    },
  ],
  // Navigation is generated from enabled sections plus fixed Home/About links.
  nav: [],
  settings: {
    siteName: 'My Blog',
    description: 'Notes about learning, work, and life.',
    author: 'Blog Author',
    email: 'admin@example.com',
  },
  issues: [],
  tools: [],
  graphics: [],
  sections: [
    {
      id: '1',
      name: 'Tech',
      slug: 'tech',
      url: '/tech',
      icon: 'code',
      color: '#4ECDC4',
      order: 1,
      enabled: true,
    },
    {
      id: '2',
      name: 'Life',
      slug: 'life',
      url: '/life',
      icon: 'coffee',
      color: '#95E1D3',
      order: 2,
      enabled: true,
    },
  ],
};

for (const name of files) {
  const target = path.join(dataDir, `${name}.json`);
  if (fs.existsSync(target)) {
    continue;
  }

  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, JSON.stringify(sampleData[name], null, 2));
  console.log(`created ${target}`);
}
