#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const dataDir = path.resolve(process.cwd(), process.env.BLOG_DATA_DIR || 'data/seed');
const files = ['posts', 'categories', 'tags', 'nav', 'settings', 'issues', 'tools', 'sections', 'graphics'];

const sampleData = {
  posts: [
    {
      id: '1',
      title: 'AI 与就业：岗位不会只消失，而是被重组',
      slug: 'ai-and-employment',
      summary: 'AI 对就业市场的影响，如何应对人工智能时代的职业挑战。',
      content: '# AI 与就业：岗位不会只消失，而是被重组\n\n## 引言\n\n人工智能的快速发展引发了人们对就业市场的担忧。然而，历史经验表明，技术革命往往会创造新的就业机会，而不仅仅是摧毁旧的。\n\n## AI 对就业的影响\n\n- **自动化**: 重复性工作将被 AI 取代\n- **增强**: 人类工作将与 AI 协作\n- **创造**: 新的职业和岗位将出现\n\n## 应对策略\n\n1. **持续学习**: 保持学习新技术的能力\n2. **跨领域合作**: 结合 AI 与人类优势\n3. **创新思维**: 寻找 AI 无法替代的价值\n\n## 结论\n\nAI 时代需要的是适应性和创造力，而不是恐惧。通过正确的心态和准备，我们可以在这个新时代找到自己的位置。',
      categories: ['1'],
      categoryIds: ['1'],
      categoryId: '1',
      tags: ['1', '2'],
      tagIds: ['1', '2'],
      status: 'published',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      created_at: new Date().toISOString().slice(0, 10),
      updated_at: new Date().toISOString().slice(0, 10),
    },
    {
      id: '2',
      title: 'Vue 3 组合式 API 最佳实践',
      slug: 'vue3-composition-api-best-practices',
      summary: 'Vue 3 组合式 API 的使用技巧和最佳实践指南。',
      content: '# Vue 3 组合式 API 最佳实践\n\n## 什么是组合式 API\n\n组合式 API 是 Vue 3 引入的新特性，它允许我们按功能组织代码，而不是按选项类型。\n\n## 核心概念\n\n- **ref**: 响应式引用\n- **reactive**: 响应式对象\n- **computed**: 计算属性\n- **watch**: 监听器\n- **生命周期钩子**\n\n## 最佳实践\n\n1. **按功能组织代码**\n2. **使用 composables 复用逻辑**\n3. **合理使用 ref 和 reactive**\n4. **优化计算属性和监听器**\n\n## 示例代码\n\n```javascript\n// 组合式 API 示例\nimport { ref, computed, onMounted } from "vue"\n\nexport function useCounter() {\n  const count = ref(0)\n  const doubleCount = computed(() => count.value * 2)\n  \n  function increment() {\n    count.value++\n  }\n  \n  onMounted(() => {\n    console.log("Counter initialized")\n  })\n  \n  return { count, doubleCount, increment }\n}\n```',
      categories: ['1'],
      categoryIds: ['1'],
      categoryId: '1',
      tags: ['1', '3'],
      tagIds: ['1', '3'],
      status: 'published',
      published: true,
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 86400000).toISOString(),
      created_at: new Date(Date.now() - 86400000).toISOString().slice(0, 10),
      updated_at: new Date(Date.now() - 86400000).toISOString().slice(0, 10),
    },
    {
      id: '3',
      title: '设计思考：如何创建有吸引力的用户界面',
      slug: 'design-thinking-ui',
      summary: '设计思考方法在用户界面设计中的应用，创建美观且实用的界面。',
      content: '# 设计思考：如何创建有吸引力的用户界面\n\n## 设计思考流程\n\n1. **同理心**: 理解用户需求\n2. **定义**: 明确问题\n3. **构思**: 生成创意\n4. **原型**: 制作模型\n5. **测试**: 收集反馈\n\n## UI 设计原则\n\n- **一致性**: 保持设计语言统一\n- **简洁性**: 减少视觉噪音\n- **层次结构**: 清晰的信息层级\n- **反馈**: 提供即时反馈\n- **可访问性**: 确保所有人都能使用\n\n## 色彩理论\n\n- **主色调**: 品牌识别\n- **辅助色**: 强调和交互\n- **中性色**: 背景和文本\n\n## 排版\n\n- **字体选择**: 可读性优先\n- **字体层级**: 建立视觉层次\n- **行高和间距**: 提升可读性\n\n## 动画和过渡\n\n- **微交互**: 增强用户体验\n- **平滑过渡**: 提升界面流畅度\n- **加载动画**: 减少等待感',
      categories: ['3'],
      categoryIds: ['3'],
      categoryId: '3',
      tags: ['4', '5'],
      tagIds: ['4', '5'],
      status: 'published',
      published: true,
      createdAt: new Date(Date.now() - 172800000).toISOString(),
      updatedAt: new Date(Date.now() - 172800000).toISOString(),
      created_at: new Date(Date.now() - 172800000).toISOString().slice(0, 10),
      updated_at: new Date(Date.now() - 172800000).toISOString().slice(0, 10),
    },
    {
      id: '4',
      title: '效率工具分享：提升开发速度的必备工具',
      slug: 'productivity-tools-for-developers',
      summary: '推荐一些能够显著提升开发效率的工具和插件。',
      content: '# 效率工具分享：提升开发速度的必备工具\n\n## 代码编辑器\n\n- **VS Code**: 轻量强大的代码编辑器\n  - 推荐插件：ESLint, Prettier, GitLens\n- **Vim/Neovim**: 高效的键盘驱动编辑器\n- **JetBrains IDEs**: 专业的IDE系列\n\n## 终端工具\n\n- **iTerm2** (Mac): 功能丰富的终端模拟器\n- **Windows Terminal** (Windows): 现代化终端\n- **Oh My Zsh**: 增强命令行体验\n\n## 版本控制\n\n- **Git**: 分布式版本控制系统\n  - 推荐工具：GitHub Desktop, SourceTree\n- **GitKraken**: 可视化Git客户端\n\n## 协作工具\n\n- **Slack**: 团队沟通\n- **Figma**: 设计协作\n- **Jira**: 项目管理\n\n## 其他工具\n\n- **Postman**: API测试\n- **Docker**: 容器化\n- **Notion**: 笔记和知识库\n\n## 配置和自动化\n\n- **dotfiles**: 统一配置管理\n- **CI/CD**: 持续集成/持续部署\n- **自动化脚本**: 减少重复工作',
      categories: ['4'],
      categoryIds: ['4'],
      categoryId: '4',
      tags: ['6', '7'],
      tagIds: ['6', '7'],
      status: 'published',
      published: true,
      createdAt: new Date(Date.now() - 259200000).toISOString(),
      updatedAt: new Date(Date.now() - 259200000).toISOString(),
      created_at: new Date(Date.now() - 259200000).toISOString().slice(0, 10),
      updated_at: new Date(Date.now() - 259200000).toISOString().slice(0, 10),
    },
    {
      id: '5',
      title: '生活随笔：程序员的日常思考',
      slug: 'life-as-a-programmer',
      summary: '记录程序员的日常生活和思考，分享工作与生活的平衡。',
      content: '# 生活随笔：程序员的日常思考\n\n## 工作与生活的平衡\n\n作为程序员，我们常常面临工作与生活平衡的挑战。长时间的编码、解决问题的压力，都可能影响我们的身心健康。\n\n## 日常习惯\n\n- **早起**: 利用清晨的时间学习和计划\n- **运动**: 保持身体活力\n- **阅读**: 拓展知识广度\n- **冥想**: 减轻压力\n- **社交**: 与朋友和家人保持联系\n\n## 学习与成长\n\n- **持续学习**: 技术发展迅速，保持学习状态\n- **项目实践**: 通过项目巩固知识\n- **分享**: 教学相长，分享知识\n- **社区参与**: 参与开源和技术社区\n\n## 职业发展\n\n- **目标设定**: 明确职业目标\n- **技能提升**: 有计划地提升技能\n- **网络建设**: 建立专业网络\n- **工作选择**: 找到适合自己的工作环境\n\n## 生活感悟\n\n- **代码之外**: 生活不仅仅是代码\n- **成就感**: 从解决问题中获得满足\n- **创造力**: 编程也是一种创作\n- **未来展望**: 保持对未来的期待',
      categories: ['5'],
      categoryIds: ['5'],
      categoryId: '5',
      tags: ['8', '9'],
      tagIds: ['8', '9'],
      status: 'published',
      published: true,
      createdAt: new Date(Date.now() - 345600000).toISOString(),
      updatedAt: new Date(Date.now() - 345600000).toISOString(),
      created_at: new Date(Date.now() - 345600000).toISOString().slice(0, 10),
      updated_at: new Date(Date.now() - 345600000).toISOString().slice(0, 10),
    },
  ],
  categories: [
    {
      id: '1',
      name: '技术笔记',
      slug: 'tech-notes',
      color: '#3498db',
      icon: 'code',
      order: 1,
      sectionId: '1',
    },
    {
      id: '2',
      name: '问题记录',
      slug: 'issues',
      color: '#e74c3c',
      icon: 'bug',
      order: 2,
      sectionId: '2',
    },
    {
      id: '3',
      name: '设计创作',
      slug: 'design',
      color: '#9b59b6',
      icon: 'palette',
      order: 3,
      sectionId: '3',
    },
    {
      id: '4',
      name: '工具分享',
      slug: 'tools',
      color: '#27ae60',
      icon: 'wrench',
      order: 4,
      sectionId: '4',
    },
    {
      id: '5',
      name: '生活随笔',
      slug: 'life',
      color: '#f39c12',
      icon: 'book',
      order: 5,
      sectionId: '5',
    },
  ],
  tags: [
    {
      id: '1',
      name: 'Vue',
      slug: 'vue',
    },
    {
      id: '2',
      name: '人工智能',
      slug: 'ai',
    },
    {
      id: '3',
      name: 'JavaScript',
      slug: 'javascript',
    },
    {
      id: '4',
      name: 'UI设计',
      slug: 'ui-design',
    },
    {
      id: '5',
      name: '设计思考',
      slug: 'design-thinking',
    },
    {
      id: '6',
      name: '效率工具',
      slug: 'productivity',
    },
    {
      id: '7',
      name: '开发工具',
      slug: 'dev-tools',
    },
    {
      id: '8',
      name: '生活感悟',
      slug: 'life-thoughts',
    },
    {
      id: '9',
      name: '职业发展',
      slug: 'career',
    },
  ],
  nav: [
    { id: 'nav-home', label: '首页', href: '/', order: 1, visible: true },
    { id: 'nav-design', label: '设计创作', href: '/design', order: 2, visible: true },
    { id: 'nav-tech', label: '技术笔记', href: '/tech', order: 3, visible: true },
    { id: 'nav-tools', label: '工具分享', href: '/tools', order: 4, visible: true },
    { id: 'nav-issues', label: '问题记录', href: '/issues', order: 5, visible: true },
    { id: 'nav-life', label: '生活随笔', href: '/life', order: 6, visible: true },
    { id: 'nav-about', label: '关于我', href: '/about', order: 7, visible: true },
  ],
  settings: {
    siteName: 'DevLog_',
    description: '记录灵感 · 设计 · 代码',
    author: 'Lemon',
    email: 'admin@example.com',
    profile: {
      name: 'Lemon',
      subtitle: '记录灵感 · 设计 · 代码',
      motto: '以持续输出为信仰，把每一次学习都变成可复用的经验。',
      avatar: '',
      coverImage: '',
      github: '',
      planet: '',
      email: 'admin@example.com',
    },
  },
  issues: [
    {
      id: '1',
      title: '示例问题：导航栏显示异常',
      description: '页面刷新时导航栏显示异常，需要修复。',
      status: 'resolved',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  tools: [
    {
      id: '1',
      name: 'VS Code',
      description: '轻量强大的代码编辑器',
      link: 'https://code.visualstudio.com/',
      icon: 'code-2',
      order: 1,
    },
  ],
  graphics: [],
  sections: [
    {
      id: '1',
      name: '技术笔记',
      slug: 'tech',
      url: '/tech',
      icon: 'code',
      color: '#4ECDC4',
      order: 1,
      enabled: true,
    },
    {
      id: '2',
      name: '问题记录',
      slug: 'issues',
      url: '/issues',
      icon: 'bug',
      color: '#FF6B6B',
      order: 2,
      enabled: true,
    },
    {
      id: '3',
      name: '设计创作',
      slug: 'design',
      url: '/design',
      icon: 'palette',
      color: '#9B59B6',
      order: 3,
      enabled: true,
    },
    {
      id: '4',
      name: '工具分享',
      slug: 'tools',
      url: '/tools',
      icon: 'wrench',
      color: '#27AE60',
      order: 4,
      enabled: true,
    },
    {
      id: '5',
      name: '生活随笔',
      slug: 'life',
      url: '/life',
      icon: 'coffee',
      color: '#F39C12',
      order: 5,
      enabled: true,
    },
  ],
};

for (const name of files) {
  const target = path.join(dataDir, `${name}.json`);
  if (fs.existsSync(target)) {
    continue;
  }

  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, JSON.stringify(sampleData[name], null, 2), 'utf8');
  console.log(`created ${target}`);
}
